arch:
  args:
    in_features: 1300
  type: Baseline
augmentation:
  type: null
data_loader:
  args:
    batch_size: 10
    dataset_loader: ChallengeData
    nworkers: 0
    shuffle: true
    test_path:
    - data/TS115_ESM1b.npz
    train_path:
    - data/Train_ESM1b.npz
    validation_split: 0.05
  type: ChallengeDataLoader
loss: secondary_structure_loss
lr_scheduler:
  type: null
metrics:
  metric_q3: 1
  metric_q8: 0
name: baseline
optimizer:
  args:
    lr: 0.0001
    weight_decay: 0
  type: Adam
save_dir: saved/
seed: 1234
target_devices:
- 0
training:
  early_stop: 3
  epochs: 50
  monitor: min val_loss
  save_period: 1
  tensorboard: true
